### ISSUE TITLE
Unable to pull from client

### ISSUE THREAD

**Issue by pwhitaker** [Bcfg2/bcfg2#410]
Debian Jessie netinstall
bcfg2-server                    1.4.0pre2~unstable~jess
python-django                  1.7.11-1+deb8u5
python-django-south        1.0-0.1
mysql-server                    5.5.62-0+deb8u1

When trying to pull from a client, I get the following error...

Unexpected instantiation failure for plugin <class 'Bcfg2.Server.Plugins.Metadata.Metadata'>
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/Bcfg2/Server/Core.py", line 427, in init_plugin
    self.plugins[plugin.name] = plugin(self)
  File "/usr/lib/python2.7/dist-packages/Bcfg2/Server/Plugins/Metadata.py", line 561, in __init__
    self.password = Bcfg2.Options.setup.password
AttributeError: 'Namespace' object has no attribute 'password'
No Metadata plugin loaded; failed to instantiate Core
Traceback (most recent call last):
  File "/usr/sbin/bcfg2-admin", line 10, in <module>
    sys.exit(CLI().run())
  File "/usr/lib/python2.7/dist-packages/Bcfg2/Server/Admin.py", line 1237, in run
    cmd.setup()
  File "/usr/lib/python2.7/dist-packages/Bcfg2/Server/Admin.py", line 768, in setup
    _ServerAdminCmd.setup(self)
  File "/usr/lib/python2.7/dist-packages/Bcfg2/Server/Admin.py", line 141, in setup
    self.core.load_plugins()
  File "/usr/lib/python2.7/dist-packages/Bcfg2/Server/Core.py", line 407, in load_plugins
    raise CoreInitError("No Metadata Plugin")
Bcfg2.Server.Core.CoreInitError: No Metadata Plugin

...also clients are not picking up on new bundles/files

**Comment by pwhitaker** [comment]
Misconfigured Bundle was the cause of clients not picking up new bundles/files

**Comment by pwhitaker** [comment]
Same when trying to extract data using minestruct...

Unexpected instantiation failure for plugin <class 'Bcfg2.Server.Plugins.Metadata.Metadata'>
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/Bcfg2/Server/Core.py", line 427, in init_plugin
    self.plugins[plugin.name] = plugin(self)
  File "/usr/lib/python2.7/dist-packages/Bcfg2/Server/Plugins/Metadata.py", line 561, in __init__
    self.password = Bcfg2.Options.setup.password
AttributeError: 'Namespace' object has no attribute 'password'
No Metadata plugin loaded; failed to instantiate Core
Traceback (most recent call last):
  File "/usr/sbin/bcfg2-admin", line 10, in <module>
    sys.exit(CLI().run())
  File "/usr/lib/python2.7/dist-packages/Bcfg2/Server/Admin.py", line 1237, in run
    cmd.setup()
  File "/usr/lib/python2.7/dist-packages/Bcfg2/Server/Admin.py", line 141, in setup
    self.core.load_plugins()
  File "/usr/lib/python2.7/dist-packages/Bcfg2/Server/Core.py", line 407, in load_plugins
    raise CoreInitError("No Metadata Plugin")
Bcfg2.Server.Core.CoreInitError: No Metadata Plugin

**Comment by AlexanderS** [comment]
This is maybe a duplicate of #376.
